from src.core_new.domain.errors import DBErrorNotFound, BadPermissions


class ProductNotFound(DBErrorNotFound): ...
class DailyProductNotFound(DBErrorNotFound): ...


class ProductNotRecordOwner(BadPermissions): ...


class DailyUserConsumptionNotRecordOwner(BadPermissions): ...


class DailyUserConsumptionNotFound(DBErrorNotFound): ...