version: "3.8"
services:
  test_db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-vol_db:/var/lib/postgresql/data:Z
    ports:
      - "5433:5432"
    networks:
      - internal-network
      - external-network

networks:
  internal-network:
    internal: true
  external-network:
    driver: bridge

volumes:
  postgres-vol:
  postgres-vol_db: