version: "3.8"
services:
  test_db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-vol_db:/var/lib/postgresql/data:Z
    ports:
      - "5433:5432"
    networks:
      - external-network
  test_meilisearch:
    image: getmeili/meilisearch:v1.9
    environment:
      - http_proxy
      - https_proxy
      - MEILI_MASTER_KEY=${MEILI_MASTER_KEY:-masterKey}
      - MEILI_NO_ANALYTICS=${MEILI_NO_ANALYTICS:-true}
      - MEILI_ENV=${MEILI_ENV:-development}
      - MEILI_LOG_LEVEL
      - MEILI_DB_PATH=${MEILI_DB_PATH:-/data.ms}
    ports:
      - "${MEILI_PORT:-7701}:7700"
    volumes:
      - ./test.ms:/data.ms
    restart: unless-stopped
    networks:
      - external-network

networks:
  external-network:
    driver: bridge

volumes:
  postgres-vol:
  postgres-vol_db: