"""create products table

Revision ID: 16f6fd3d593b
Revises: dc187fcb5bff
Create Date: 2023-01-29 21:33:00.069006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16f6fd3d593b'
down_revision = 'dc187fcb5bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('en.openfoodfacts.org.products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('en.openfoodfacts.org.products',
    sa.Column('code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('abbreviated_product_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('generic_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('packaging', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('packaging_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('packaging_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('packaging_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brands', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brands_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categories', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categories_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categories_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('origins', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('origins_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('origins_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manufacturing_places', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manufacturing_places_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('labels', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('labels_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('labels_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emb_codes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('emb_codes_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('first_packaging_code_geo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cities_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('purchase_places', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('countries', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('countries_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('countries_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ingredients_analysis_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('serving_size', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('serving_quantity', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('no_nutrition_data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additives_n', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('additives', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additives_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additives_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nutriscore_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nutriscore_grade', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('food_groups', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('food_groups_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('food_groups_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('states', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('states_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('states_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('brand_owner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('nutrient_levels_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('product_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('unique_scans_n', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('popularity_tags', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('completeness', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('main_category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('main_category_en', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('image_small_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('energy-kj_100g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('energy-kcal_100g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('energy_100g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('energy-from-fat_100g', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fat_100g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('saturated-fat_100g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('carbohydrates_100g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sugars_100g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('added-sugars_100g', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sucrose_100g', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('glucose_100g', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fructose_100g', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('lactose_100g', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proteins_100g', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('casein_100g', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('salt_100g', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
