"""messagesv2

Revision ID: 20c062112d26
Revises: d0820a5af84e
Create Date: 2023-05-13 14:25:03.262249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20c062112d26'
down_revision = 'd0820a5af84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
