"""recipe-with-products

Revision ID: 379b671b05c7
Revises: 6c9aedb3522f
Create Date: 2023-09-23 11:41:11.963991

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '379b671b05c7'
down_revision = '6c9aedb3522f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_for_recipe',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('weight_in_grams', sa.Float(), nullable=False),
                    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('recipe_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('product_recipe_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_recipe_association',
                    sa.Column('product_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True),
                    sa.Column('recipe_id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'],
                                            name='product_recipe_association_product_id_fkey'),
                    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'],
                                            name='product_recipe_association_recipe_id_fkey')
                    )
    op.drop_table('product_for_recipe')
    # ### end Alembic commands ###
