"""dayv3

Revision ID: 618a900c6829
Revises: 7f425db49acd
Create Date: 2023-04-09 19:42:11.001158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '618a900c6829'
down_revision = '7f425db49acd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
