"""dayv5

Revision ID: 646e6f3b3775
Revises: 618a900c6829
Create Date: 2023-04-09 19:44:34.905197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646e6f3b3775'
down_revision = '618a900c6829'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
