"""dayv2

Revision ID: 77d15ffd4c5a
Revises: fede715d4649
Create Date: 2023-04-09 19:36:17.640489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d15ffd4c5a'
down_revision = 'fede715d4649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
