"""dayv3

Revision ID: 7f425db49acd
Revises: 77d15ffd4c5a
Create Date: 2023-04-09 19:37:31.974835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f425db49acd'
down_revision = '77d15ffd4c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
