"""create products table v2

Revision ID: 892c6b19036d
Revises: 16f6fd3d593b
Create Date: 2023-01-29 21:34:39.091482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '892c6b19036d'
down_revision = '16f6fd3d593b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('code', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('size', sa.Text(), nullable=True),
    sa.Column('groups', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('energy_kcal_100g', sa.Float(), nullable=False),
    sa.Column('fat_100g', sa.Float(), nullable=True),
    sa.Column('carbohydrates_100g', sa.Float(), nullable=True),
    sa.Column('sugars_100g', sa.Float(), nullable=True),
    sa.Column('proteins_100g', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
