"""daily

Revision ID: 9158937110b7
Revises: e25cbd4e72f9
Create Date: 2023-04-09 16:26:30.016027

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils
from src.modules.products.infra.models.product import UserProductType

# revision identifiers, used by Alembic.
revision = '9158937110b7'
down_revision = 'e25cbd4e72f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_user_products',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('product_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('weight_in_grams', sa.Float(), nullable=False),
                    sa.Column('time_updated', sa.DateTime(), nullable=True),
                    sa.Column('date', sa.DateTime(), nullable=True),
                    sa.Column('type', sqlalchemy_utils.types.choice.ChoiceType(UserProductType, impl=sa.Integer()),
                              nullable=True),
                    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_user_products')
    # ### end Alembic commands ###
