"""messagesv5

Revision ID: 9fffbc2dba32
Revises: a5cde7ec587d
Create Date: 2023-05-13 17:43:04.787352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fffbc2dba32'
down_revision = 'a5cde7ec587d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
