"""messagesv3

Revision ID: b0115bad29ec
Revises: 20c062112d26
Create Date: 2023-05-13 16:17:37.371225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0115bad29ec'
down_revision = '20c062112d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channel', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_column('channel', 'participants_id')
    op.add_column('channel', sa.Column('participants_id', postgresql.ARRAY(postgresql.UUID()), nullable=False))
    op.drop_column('channel', 'channel_id')
    op.add_column('message', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'created_at')
    op.add_column('channel', sa.Column('channel_id', sa.TEXT(), autoincrement=False, nullable=False))
    op.alter_column('channel', 'participants_id',
                    existing_type=sa.ARRAY(postgresql.UUID()),
                    type_=postgresql.ARRAY(sa.INTEGER()),
                    existing_nullable=False)
    op.drop_column('channel', 'created_at')
    # ### end Alembic commands ###
