"""recipe-with-products-v2

Revision ID: f5c12f9558b9
Revises: 379b671b05c7
Create Date: 2023-09-23 16:14:34.247825

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f5c12f9558b9"
down_revision = "379b671b05c7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "product_for_recipe", sa.Column("calories", sa.Float(), nullable=True)
    )
    op.add_column(
        "product_for_recipe", sa.Column("proteins", sa.Float(), nullable=True)
    )
    op.add_column("product_for_recipe", sa.Column("fats", sa.Float(), nullable=True))
    op.add_column(
        "product_for_recipe", sa.Column("carbohydrates", sa.Float(), nullable=True)
    )
    op.add_column("recipes", sa.Column("summary_calories", sa.Float(), nullable=True))
    op.add_column("recipes", sa.Column("summary_proteins", sa.Float(), nullable=True))
    op.add_column("recipes", sa.Column("summary_fats", sa.Float(), nullable=True))
    op.add_column(
        "recipes", sa.Column("summary_carbohydrates", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "summary_carbohydrates")
    op.drop_column("recipes", "summary_fats")
    op.drop_column("recipes", "summary_proteins")
    op.drop_column("recipes", "summary_calories")
    op.drop_column("product_for_recipe", "carbohydrates")
    op.drop_column("product_for_recipe", "fats")
    op.drop_column("product_for_recipe", "proteins")
    op.drop_column("product_for_recipe", "calories")
    # ### end Alembic commands ###
