"""daily_v2

Revision ID: fede715d4649
Revises: 9158937110b7
Create Date: 2023-04-09 17:17:34.622371

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fede715d4649'
down_revision = '9158937110b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_user_consumption',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('time_updated', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('summary_calories', sa.Float(), nullable=True),
    sa.Column('summary_proteins', sa.Float(), nullable=True),
    sa.Column('summary_fats', sa.Float(), nullable=True),
    sa.Column('summary_carbohydrates', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('daily_calories', sa.Float(), nullable=True),
    sa.Column('daily_proteins', sa.Float(), nullable=True),
    sa.Column('daily_fats', sa.Float(), nullable=True),
    sa.Column('daily_carbohydrates', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'user_id')
    )
    op.add_column('daily_user_products', sa.Column('day_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('daily_user_products', sa.Column('calories', sa.Float(), nullable=True))
    op.add_column('daily_user_products', sa.Column('proteins', sa.Float(), nullable=True))
    op.add_column('daily_user_products', sa.Column('fats', sa.Float(), nullable=True))
    op.add_column('daily_user_products', sa.Column('carbohydrates', sa.Float(), nullable=True))
    op.drop_constraint('daily_user_products_user_id_fkey', 'daily_user_products', type_='foreignkey')
    op.create_foreign_key(None, 'daily_user_products', 'daily_user_consumption', ['day_id'], ['id'])
    op.drop_column('daily_user_products', 'user_id')
    op.drop_column('daily_user_products', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_user_products', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('daily_user_products', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'daily_user_products', type_='foreignkey')
    op.create_foreign_key('daily_user_products_user_id_fkey', 'daily_user_products', 'user', ['user_id'], ['id'])
    op.drop_column('daily_user_products', 'carbohydrates')
    op.drop_column('daily_user_products', 'fats')
    op.drop_column('daily_user_products', 'proteins')
    op.drop_column('daily_user_products', 'calories')
    op.drop_column('daily_user_products', 'day_id')
    op.drop_table('user_settings')
    op.drop_table('daily_user_consumption')
    # ### end Alembic commands ###
