name: Palumi
on:
  push:
jobs:
  update:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.8
          cache: pip
      - name: Install requirements
        run: pip install -r ./requirements.txt
      - name: Prepare test db
        run: typer deployment.py run run-db --test
      - name: Run tests
        run: typer deployment.py run test